// Generated by scripts/emit_ts.py from schema/part.schema.json + data/.
// Do not edit by hand: CI regenerates this file and fails on any difference.

export type Namespace = "boards" | "electronic" | "mechanical" | "material";

export interface PartSource {
  citation: string;
  retrieved?: string;
  upstream_schema_version?: number | string;
}

export interface Part {
  schema_version: 0;
  id: string;
  namespace: Namespace;
  name: string;
  description?: string;
  source: PartSource;
  attributes?: Record<string, unknown>;
  links?: Record<string, string>;
}

export const PARTS: readonly Part[] = Object.freeze([
  {
    "schema_version": 0,
    "id": "boards/adafruit-feather-esp32s3-tft",
    "namespace": "boards",
    "name": "adafruit-feather-esp32s3-tft",
    "description": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz, 1.14\" ST7789 240x135 TFT, LiPo charge (CircuitPython VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9114,
          "pid": 33053,
          "architecture": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz, 1.14\" ST7789 240x135 TFT, LiPo charge (CircuitPython VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "battery",
        "ble",
        "display",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "featherwing",
        "stemma_qt"
      ],
      "vendor": "Adafruit",
      "ecosystem": "Feather",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/adafruit-qtpy-esp32s3",
    "namespace": "boards",
    "name": "adafruit-qtpy-esp32s3",
    "description": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz (CircuitPython VID/PID; Arduino mode = 0x303a:0x1001)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9114,
          "pid": 33091,
          "architecture": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz (CircuitPython VID/PID; Arduino mode = 0x303a:0x1001)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "stemma_qt"
      ],
      "vendor": "Adafruit",
      "ecosystem": "QT Py",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-leonardo",
    "namespace": "boards",
    "name": "arduino-leonardo",
    "description": "AVR ATmega32U4 @ 16 MHz (native USB)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 54,
          "architecture": "AVR ATmega32U4 @ 16 MHz (native USB)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Leonardo",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-mega",
    "namespace": "boards",
    "name": "arduino-mega",
    "description": "AVR ATmega2560 @ 16 MHz",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 66,
          "architecture": "AVR ATmega2560 @ 16 MHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Mega",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-nano",
    "namespace": "boards",
    "name": "arduino-nano",
    "description": "AVR ATmega328P @ 16 MHz (CH340 USB-UART)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6790,
          "pid": 29987,
          "architecture": "AVR ATmega328P @ 16 MHz (CH340 USB-UART)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Nano",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-nano-33-ble",
    "namespace": "boards",
    "name": "arduino-nano-33-ble",
    "description": "nRF52840 ARM Cortex-M4F @ 64 MHz (BLE, IMU)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 32858,
          "architecture": "nRF52840 ARM Cortex-M4F @ 64 MHz (BLE, IMU)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "sensor_read",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Nano",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-nano-esp32",
    "namespace": "boards",
    "name": "arduino-nano-esp32",
    "description": "ESP32-S3 (u-blox NORA-W106) Xtensa LX7 dual-core @ 240 MHz, Nano form factor",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 112,
          "architecture": "ESP32-S3 (u-blox NORA-W106) Xtensa LX7 dual-core @ 240 MHz, Nano form factor"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Nano",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-nano-every",
    "namespace": "boards",
    "name": "arduino-nano-every",
    "description": "AVR ATmega4809 @ 20 MHz",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 88,
          "architecture": "AVR ATmega4809 @ 20 MHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Nano",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-uno",
    "namespace": "boards",
    "name": "arduino-uno",
    "description": "AVR ATmega328P @ 16 MHz (legacy)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 1,
          "architecture": "AVR ATmega328P @ 16 MHz (legacy)"
        },
        {
          "vid": 9025,
          "pid": 67,
          "architecture": "AVR ATmega328P @ 16 MHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Uno",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/arduino-uno-q",
    "namespace": "boards",
    "name": "arduino-uno-q",
    "description": "Arduino Uno Q / ATmega328P",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9025,
          "pid": 120,
          "architecture": "Arduino Uno Q / ATmega328P"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Arduino",
      "ecosystem": "Uno",
      "transport": "bridge"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/beaglebone-black",
    "namespace": "boards",
    "name": "beaglebone-black",
    "description": "TI AM3358 ARM Cortex-A8 @ 1 GHz",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 7531,
          "pid": 260,
          "architecture": "TI AM3358 ARM Cortex-A8 @ 1 GHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "can",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "BeagleBoard",
      "ecosystem": "BeagleBone",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/coral-dev-board-mini",
    "namespace": "boards",
    "name": "coral-dev-board-mini",
    "description": "MediaTek MT8167S quad Cortex-A35 + Google Edge TPU, 4 TOPS, 2 GB LPDDR3 (AArch64)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1317,
          "pid": 42151,
          "architecture": "MediaTek MT8167S quad Cortex-A35 + Google Edge TPU, 4 TOPS, 2 GB LPDDR3 (AArch64)"
        }
      ],
      "capabilities": [
        "ble",
        "camera_capture",
        "edge_tpu",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "hat_pi"
      ],
      "vendor": "Google",
      "ecosystem": "Coral",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/coral-usb-accelerator",
    "namespace": "boards",
    "name": "coral-usb-accelerator",
    "description": "Google Edge TPU ASIC, 4 TOPS @ 2 W (USB 3.0 coprocessor)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6353,
          "pid": 37634,
          "architecture": "Google Edge TPU ASIC, 4 TOPS @ 2 W (USB 3.0 coprocessor)"
        }
      ],
      "capabilities": [
        "edge_tpu"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Google",
      "ecosystem": "Coral",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/cp2102",
    "namespace": "boards",
    "name": "cp2102",
    "description": "Silicon Labs CP2102 USB-UART bridge",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 4292,
          "pid": 60000,
          "architecture": "Silicon Labs CP2102 USB-UART bridge"
        }
      ],
      "capabilities": [],
      "connectors": [
        "bare"
      ],
      "vendor": "Silicon Labs",
      "ecosystem": "USB-UART",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/cp2102n",
    "namespace": "boards",
    "name": "cp2102n",
    "description": "Silicon Labs CP2102N USB-UART bridge",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 4292,
          "pid": 60016,
          "architecture": "Silicon Labs CP2102N USB-UART bridge"
        }
      ],
      "capabilities": [],
      "connectors": [
        "bare"
      ],
      "vendor": "Silicon Labs",
      "ecosystem": "USB-UART",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/cyd-esp32-2432s028r",
    "namespace": "boards",
    "name": "cyd-esp32-2432s028r",
    "description": "ESP32 'Cheap Yellow Display' (ESP32-2432S028R): ILI9341 320x240 + XPT2046 resistive touch, microSD (CH340; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6790,
          "pid": 29987,
          "architecture": "ESP32 'Cheap Yellow Display' (ESP32-2432S028R): ILI9341 320x240 + XPT2046 resistive touch, microSD (CH340; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "display",
        "gpio",
        "i2c",
        "microsd",
        "spi",
        "touch",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Sunton",
      "ecosystem": "Cheap Yellow Display",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/dfrobot-firebeetle2-esp32s3",
    "namespace": "boards",
    "name": "dfrobot-firebeetle2-esp32s3",
    "description": "ESP32-S3 LX7 dual-core @ 240 MHz, LiPo charge, onboard GDI (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 LX7 dual-core @ 240 MHz, LiPo charge, onboard GDI (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "battery",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "DFRobot",
      "ecosystem": "FireBeetle",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32",
    "namespace": "boards",
    "name": "esp32",
    "description": "ESP32 Xtensa LX6 @ 240 MHz (CH340)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6790,
          "pid": 21972,
          "architecture": "ESP32 Xtensa LX6 @ 240 MHz (CH340)"
        }
      ],
      "capabilities": [
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-c3",
    "namespace": "boards",
    "name": "esp32-c3",
    "description": "ESP32-C3 RISC-V single-core @ 160 MHz (native USB)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-C3 RISC-V single-core @ 160 MHz (native USB)"
        }
      ],
      "capabilities": [
        "ble",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-C3",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-c5",
    "namespace": "boards",
    "name": "esp32-c5",
    "description": "ESP32-C5 RISC-V single-core @ 240 MHz (dual-band 2.4/5 GHz Wi-Fi 6, BLE 5, 802.15.4; native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-C5 RISC-V single-core @ 240 MHz (dual-band 2.4/5 GHz Wi-Fi 6, BLE 5, 802.15.4; native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "thread",
        "wifi",
        "zigbee"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-C5",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-c6",
    "namespace": "boards",
    "name": "esp32-c6",
    "description": "ESP32-C6 RISC-V single-core @ 160 MHz (Wi-Fi 6, BLE 5, 802.15.4; native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-C6 RISC-V single-core @ 160 MHz (Wi-Fi 6, BLE 5, 802.15.4; native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "thread",
        "wifi",
        "zigbee"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-C6",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-cam",
    "namespace": "boards",
    "name": "esp32-cam",
    "description": "ESP32 + OV2640 camera, microSD (AI-Thinker; flashed via external USB-UART; VID/PID is a common CH340 programmer)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6790,
          "pid": 29987,
          "architecture": "ESP32 + OV2640 camera, microSD (AI-Thinker; flashed via external USB-UART; VID/PID is a common CH340 programmer)"
        }
      ],
      "capabilities": [
        "camera_capture",
        "gpio",
        "microsd",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "AI-Thinker",
      "ecosystem": "ESP32-CAM",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-h2",
    "namespace": "boards",
    "name": "esp32-h2",
    "description": "ESP32-H2 RISC-V single-core @ 96 MHz (BLE 5, 802.15.4, no Wi-Fi; native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-H2 RISC-V single-core @ 96 MHz (BLE 5, 802.15.4, no Wi-Fi; native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "thread",
        "zigbee"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-H2",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-p4",
    "namespace": "boards",
    "name": "esp32-p4",
    "description": "ESP32-P4 dual-core RISC-V @ 400 MHz (AI vector ext., MIPI-CSI/DSI, no radio; native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-P4 dual-core RISC-V @ 400 MHz (AI vector ext., MIPI-CSI/DSI, no radio; native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "camera_capture",
        "display",
        "gpio",
        "i2c",
        "nn_accel",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-P4",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-s3",
    "namespace": "boards",
    "name": "esp32-s3",
    "description": "ESP32-S3 (CP2102 USB-UART)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 4292,
          "pid": 60000,
          "architecture": "ESP32-S3 (CP2102 USB-UART)"
        },
        {
          "vid": 6790,
          "pid": 21971,
          "architecture": "ESP32-S3 (CH343 USB-UART)"
        },
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 Xtensa LX7 @ 240 MHz (native USB)"
        }
      ],
      "capabilities": [
        "audio_sample",
        "camera_capture",
        "gpio",
        "sensor_read"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-S3",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/esp32-s3-cam",
    "namespace": "boards",
    "name": "esp32-s3-cam",
    "description": "ESP32-S3 + OV2640/OV5640 camera, microSD, PSRAM (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 + OV2640/OV5640 camera, microSD, PSRAM (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "camera_capture",
        "gpio",
        "i2c",
        "microsd",
        "psram",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Espressif",
      "ecosystem": "ESP32-S3",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/flipper-zero",
    "namespace": "boards",
    "name": "flipper-zero",
    "description": "STM32WB55 ARM Cortex-M4 @ 64 MHz (multi-tool; USB CDC)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 22336,
          "architecture": "STM32WB55 ARM Cortex-M4 @ 64 MHz (multi-tool; USB CDC)"
        }
      ],
      "capabilities": [
        "ble",
        "gpio",
        "ibutton",
        "infrared",
        "nfc",
        "rfid",
        "subghz"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Flipper Devices",
      "ecosystem": "Flipper Zero",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/ftdi-ft231x",
    "namespace": "boards",
    "name": "ftdi-ft231x",
    "description": "FTDI FT231X USB-UART bridge",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1027,
          "pid": 24597,
          "architecture": "FTDI FT231X USB-UART bridge"
        }
      ],
      "capabilities": [],
      "connectors": [
        "bare"
      ],
      "vendor": "FTDI",
      "ecosystem": "USB-UART",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/ftdi-ft232",
    "namespace": "boards",
    "name": "ftdi-ft232",
    "description": "FTDI FT232 USB-UART bridge",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1027,
          "pid": 24577,
          "architecture": "FTDI FT232 USB-UART bridge"
        }
      ],
      "capabilities": [],
      "connectors": [
        "bare"
      ],
      "vendor": "FTDI",
      "ecosystem": "USB-UART",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/heltec-wifi-lora-32-v3",
    "namespace": "boards",
    "name": "heltec-wifi-lora-32-v3",
    "description": "ESP32-S3 + SX1262 LoRa + 0.96\" OLED (Meshtastic-compatible; native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 + SX1262 LoRa + 0.96\" OLED (Meshtastic-compatible; native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "display",
        "gpio",
        "i2c",
        "lora",
        "mesh",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Heltec",
      "ecosystem": "WiFi LoRa 32",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/jetson-nano",
    "namespace": "boards",
    "name": "jetson-nano",
    "description": "NVIDIA Tegra X1 quad-core ARM Cortex-A57 @ 1.43 GHz (128-core Maxwell GPU)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 2389,
          "pid": 28704,
          "architecture": "NVIDIA Tegra X1 quad-core ARM Cortex-A57 @ 1.43 GHz (128-core Maxwell GPU)"
        }
      ],
      "capabilities": [
        "camera_capture",
        "cuda",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "NVIDIA",
      "ecosystem": "Jetson",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/jetson-orin-nano",
    "namespace": "boards",
    "name": "jetson-orin-nano",
    "description": "NVIDIA Jetson Orin Nano: 6-core Arm Cortex-A78AE + 1024-core Ampere GPU w/ tensor cores, 67 TOPS (AArch64)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 2389,
          "pid": 28704,
          "architecture": "NVIDIA Jetson Orin Nano: 6-core Arm Cortex-A78AE + 1024-core Ampere GPU w/ tensor cores, 67 TOPS (AArch64)"
        }
      ],
      "capabilities": [
        "camera_capture",
        "cuda",
        "gpio",
        "i2c",
        "pwm",
        "spi",
        "tensor_rt"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "NVIDIA",
      "ecosystem": "Jetson",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/lilygo-t-beam",
    "namespace": "boards",
    "name": "lilygo-t-beam",
    "description": "ESP32 + SX1276/SX1262 LoRa + NEO-6M GPS (Meshtastic-compatible; CP210x; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 4292,
          "pid": 60000,
          "architecture": "ESP32 + SX1276/SX1262 LoRa + NEO-6M GPS (Meshtastic-compatible; CP210x; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "gpio",
        "gps",
        "i2c",
        "lora",
        "mesh",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "LILYGO",
      "ecosystem": "T-Beam",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/lilygo-t-deck",
    "namespace": "boards",
    "name": "lilygo-t-deck",
    "description": "ESP32-S3 LX7 dual-core @ 240 MHz + SX1262 LoRa, 2.8\" IPS touch, keyboard/trackball, 16 MB flash / 8 MB PSRAM (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 LX7 dual-core @ 240 MHz + SX1262 LoRa, 2.8\" IPS touch, keyboard/trackball, 16 MB flash / 8 MB PSRAM (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "audio_output",
        "audio_sample",
        "battery",
        "ble",
        "display",
        "gpio",
        "i2c",
        "keyboard",
        "lora",
        "microsd",
        "psram",
        "spi",
        "touch",
        "trackball",
        "wifi"
      ],
      "connectors": [
        "bare",
        "grove"
      ],
      "vendor": "LILYGO",
      "ecosystem": "T-Deck",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/lilygo-t-deck-plus",
    "namespace": "boards",
    "name": "lilygo-t-deck-plus",
    "description": "ESP32-S3 LX7 dual-core @ 240 MHz + SX1262 LoRa + GNSS, 2.8\" IPS touch, keyboard/trackball, 2000 mAh (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 LX7 dual-core @ 240 MHz + SX1262 LoRa + GNSS, 2.8\" IPS touch, keyboard/trackball, 2000 mAh (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "audio_output",
        "audio_sample",
        "battery",
        "ble",
        "display",
        "gpio",
        "gps",
        "i2c",
        "keyboard",
        "lora",
        "microsd",
        "psram",
        "spi",
        "touch",
        "trackball",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "LILYGO",
      "ecosystem": "T-Deck",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/lilygo-t-display-s3",
    "namespace": "boards",
    "name": "lilygo-t-display-s3",
    "description": "ESP32-S3 LX7 dual-core @ 240 MHz, 1.9\" ST7789 320x170 LCD, 16 MB flash / 8 MB PSRAM (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 LX7 dual-core @ 240 MHz, 1.9\" ST7789 320x170 LCD, 16 MB flash / 8 MB PSRAM (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "display",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "LILYGO",
      "ecosystem": "T-Display",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/lilygo-t-lora-pager",
    "namespace": "boards",
    "name": "lilygo-t-lora-pager",
    "description": "ESP32-S3 @ 240 MHz + SX1262 LoRa, keyboard + rotary encoder, GPS, NFC, IMU (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 @ 240 MHz + SX1262 LoRa, keyboard + rotary encoder, GPS, NFC, IMU (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "audio_output",
        "battery",
        "ble",
        "display",
        "gpio",
        "gps",
        "i2c",
        "imu",
        "keyboard",
        "lora",
        "mesh",
        "microsd",
        "nfc",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "LILYGO",
      "ecosystem": "T-Lora",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/m5stack-atom-s3",
    "namespace": "boards",
    "name": "m5stack-atom-s3",
    "description": "ESP32-S3 @ 240 MHz, 0.85\" LCD, compact (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-S3 @ 240 MHz, 0.85\" LCD, compact (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "display",
        "gpio",
        "i2c",
        "spi",
        "wifi"
      ],
      "connectors": [
        "grove"
      ],
      "vendor": "M5Stack",
      "ecosystem": "M5 Atom",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/m5stack-cardputer",
    "namespace": "boards",
    "name": "m5stack-cardputer",
    "description": "M5StampS3 (ESP32-S3) @ 240 MHz, 56-key keyboard, 1.14\" ST7789, mic + speaker, IR TX (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "M5StampS3 (ESP32-S3) @ 240 MHz, 56-key keyboard, 1.14\" ST7789, mic + speaker, IR TX (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "audio_output",
        "audio_sample",
        "battery",
        "ble",
        "display",
        "gpio",
        "i2c",
        "infrared",
        "keyboard",
        "microsd",
        "spi",
        "wifi"
      ],
      "connectors": [
        "grove"
      ],
      "vendor": "M5Stack",
      "ecosystem": "Cardputer",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/m5stack-core2",
    "namespace": "boards",
    "name": "m5stack-core2",
    "description": "ESP32-D0WDQ6 @ 240 MHz, 2.0\" ILI9342C touch LCD, MPU6886 IMU (CP2104; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 4292,
          "pid": 60000,
          "architecture": "ESP32-D0WDQ6 @ 240 MHz, 2.0\" ILI9342C touch LCD, MPU6886 IMU (CP2104; shared VID/PID)"
        }
      ],
      "capabilities": [
        "ble",
        "display",
        "gpio",
        "i2c",
        "imu",
        "microsd",
        "spi",
        "touch",
        "wifi"
      ],
      "connectors": [
        "grove",
        "mbus"
      ],
      "vendor": "M5Stack",
      "ecosystem": "M5 Core",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/m5stack-module-llm",
    "namespace": "boards",
    "name": "m5stack-module-llm",
    "description": "AXera AX630C dual Cortex-A53 @ 1.2 GHz + 3.2 TOPS NPU, 4 GB LPDDR4, 32 GB eMMC (CH340N; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6790,
          "pid": 29987,
          "architecture": "AXera AX630C dual Cortex-A53 @ 1.2 GHz + 3.2 TOPS NPU, 4 GB LPDDR4, 32 GB eMMC (CH340N; shared VID/PID)"
        }
      ],
      "capabilities": [
        "audio_output",
        "audio_sample",
        "ethernet",
        "npu"
      ],
      "connectors": [
        "mbus"
      ],
      "vendor": "M5Stack",
      "ecosystem": "Module",
      "transport": "bridge"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/m5stack-tab5",
    "namespace": "boards",
    "name": "m5stack-tab5",
    "description": "ESP32-P4 dual RISC-V @ 400 MHz + ESP32-C6 radio co-proc; 5\" 1280x720 MIPI-DSI touch, 2MP camera (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-P4 dual RISC-V @ 400 MHz + ESP32-C6 radio co-proc; 5\" 1280x720 MIPI-DSI touch, 2MP camera (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "audio_output",
        "audio_sample",
        "battery",
        "ble",
        "camera_capture",
        "display",
        "gpio",
        "i2c",
        "microsd",
        "nn_accel",
        "psram",
        "spi",
        "touch",
        "wifi"
      ],
      "connectors": [
        "grove",
        "mbus"
      ],
      "vendor": "M5Stack",
      "ecosystem": "Tab",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nanopi-neo3",
    "namespace": "boards",
    "name": "nanopi-neo3",
    "description": "Rockchip RK3328 quad-core ARM Cortex-A53 @ 1.5 GHz (AArch64)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 8711,
          "pid": 13068,
          "architecture": "Rockchip RK3328 quad-core ARM Cortex-A53 @ 1.5 GHz (AArch64)"
        }
      ],
      "capabilities": [
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "FriendlyELEC",
      "ecosystem": "NanoPi",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nrf52840-dk",
    "namespace": "boards",
    "name": "nrf52840-dk",
    "description": "Nordic nRF52840 ARM Cortex-M4F @ 64 MHz (BLE 5.0)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 4966,
          "pid": 4117,
          "architecture": "Nordic nRF52840 ARM Cortex-M4F @ 64 MHz (BLE 5.0)"
        }
      ],
      "capabilities": [
        "ble",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Nordic Semiconductor",
      "ecosystem": "nRF DK",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nucleo-f401re",
    "namespace": "boards",
    "name": "nucleo-f401re",
    "description": "ARM Cortex-M4 @ 84 MHz (STM32F401RE)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 14155,
          "architecture": "ARM Cortex-M4 @ 84 MHz (STM32F401RE)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "flash",
        "gpio",
        "i2c",
        "pwm",
        "rtt",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "STMicroelectronics",
      "ecosystem": "Nucleo-64",
      "transport": "probe"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nucleo-f411re",
    "namespace": "boards",
    "name": "nucleo-f411re",
    "description": "ARM Cortex-M4 @ 100 MHz (STM32F411RE)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 14158,
          "architecture": "ARM Cortex-M4 @ 100 MHz (STM32F411RE)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "flash",
        "gpio",
        "i2c",
        "pwm",
        "rtt",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "STMicroelectronics",
      "ecosystem": "Nucleo-64",
      "transport": "probe"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nucleo-g474re",
    "namespace": "boards",
    "name": "nucleo-g474re",
    "description": "ARM Cortex-M4 @ 170 MHz (STM32G474RE, HRTIM)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 14156,
          "architecture": "ARM Cortex-M4 @ 170 MHz (STM32G474RE, HRTIM)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "flash",
        "gpio",
        "i2c",
        "pwm",
        "rtt",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "STMicroelectronics",
      "ecosystem": "Nucleo-64",
      "transport": "probe"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nucleo-h743zi",
    "namespace": "boards",
    "name": "nucleo-h743zi",
    "description": "ARM Cortex-M7 @ 480 MHz (STM32H743ZI)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 14157,
          "architecture": "ARM Cortex-M7 @ 480 MHz (STM32H743ZI)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "flash",
        "gpio",
        "i2c",
        "pwm",
        "rtt",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "STMicroelectronics",
      "ecosystem": "Nucleo-144",
      "transport": "probe"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/nucleo-l476rg",
    "namespace": "boards",
    "name": "nucleo-l476rg",
    "description": "ARM Cortex-M4 @ 80 MHz (STM32L476RG, ultra-low-power)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 14159,
          "architecture": "ARM Cortex-M4 @ 80 MHz (STM32L476RG, ultra-low-power)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "flash",
        "gpio",
        "i2c",
        "pwm",
        "rtt",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "STMicroelectronics",
      "ecosystem": "Nucleo-64",
      "transport": "probe"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/oak-d-lite",
    "namespace": "boards",
    "name": "oak-d-lite",
    "description": "Intel Movidius Myriad X VPU, 1.4 TOPS; 12.3MP RGB + 2x 480p stereo depth (USB 3)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 999,
          "pid": 9349,
          "architecture": "Intel Movidius Myriad X VPU, 1.4 TOPS; 12.3MP RGB + 2x 480p stereo depth (USB 3)"
        }
      ],
      "capabilities": [
        "camera_capture",
        "vpu"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Luxonis",
      "ecosystem": "OAK",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/pimoroni-presto",
    "namespace": "boards",
    "name": "pimoroni-presto",
    "description": "RP2350 dual Cortex-M33 @ 150 MHz + RM2 Wi-Fi/BLE, 4\" 480x480 IPS touch (MicroPython VID/PID; shared)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 11914,
          "pid": 5,
          "architecture": "RP2350 dual Cortex-M33 @ 150 MHz + RM2 Wi-Fi/BLE, 4\" 480x480 IPS touch (MicroPython VID/PID; shared)"
        }
      ],
      "capabilities": [
        "audio_output",
        "battery",
        "ble",
        "display",
        "gpio",
        "i2c",
        "microsd",
        "spi",
        "touch",
        "wifi"
      ],
      "connectors": [
        "qwiic"
      ],
      "vendor": "Pimoroni",
      "ecosystem": "Presto",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/radxa-rock-5b",
    "namespace": "boards",
    "name": "radxa-rock-5b",
    "description": "Rockchip RK3588 octa-core (4x Cortex-A76 + 4x Cortex-A55), Mali-G610, 6 TOPS NPU (AArch64)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 8711,
          "pid": 13578,
          "architecture": "Rockchip RK3588 octa-core (4x Cortex-A76 + 4x Cortex-A55), Mali-G610, 6 TOPS NPU (AArch64)"
        }
      ],
      "capabilities": [
        "ethernet",
        "gpio",
        "i2c",
        "npu",
        "pwm",
        "spi"
      ],
      "connectors": [
        "hat_pi"
      ],
      "vendor": "Radxa",
      "ecosystem": "ROCK",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/rak4631",
    "namespace": "boards",
    "name": "rak4631",
    "description": "Nordic nRF52840 + Semtech SX1262 LoRa (RAKwireless WisBlock core; Meshtastic-compatible; Adafruit nRF52 UF2 bootloader VID/PID, shared — selected by name)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 9114,
          "pid": 41,
          "architecture": "Nordic nRF52840 + Semtech SX1262 LoRa (RAKwireless WisBlock core; Meshtastic-compatible; Adafruit nRF52 UF2 bootloader VID/PID, shared — selected by name)"
        }
      ],
      "capabilities": [
        "ble",
        "gpio",
        "i2c",
        "lora",
        "mesh",
        "nfc",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "RAKwireless",
      "ecosystem": "WisBlock",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/raspberry-pi-4",
    "namespace": "boards",
    "name": "raspberry-pi-4",
    "description": "BCM2711 quad-core ARM Cortex-A72 @ 1.8 GHz (AArch64)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 8457,
          "pid": 2071,
          "architecture": "BCM2711 quad-core ARM Cortex-A72 @ 1.8 GHz (AArch64)"
        }
      ],
      "capabilities": [
        "camera_capture",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "hat_pi"
      ],
      "vendor": "Raspberry Pi",
      "ecosystem": "Raspberry Pi",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/raspberry-pi-5",
    "namespace": "boards",
    "name": "raspberry-pi-5",
    "description": "BCM2712 quad-core ARM Cortex-A76 @ 2.4 GHz (AArch64)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 8457,
          "pid": 2080,
          "architecture": "BCM2712 quad-core ARM Cortex-A76 @ 2.4 GHz (AArch64)"
        }
      ],
      "capabilities": [
        "camera_capture",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "hat_pi"
      ],
      "vendor": "Raspberry Pi",
      "ecosystem": "Raspberry Pi",
      "transport": "native"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/raspberry-pi-pico",
    "namespace": "boards",
    "name": "raspberry-pi-pico",
    "description": "RP2040 dual-core ARM Cortex-M0+ @ 133 MHz",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 11914,
          "pid": 3,
          "architecture": "RP2040 dual-core ARM Cortex-M0+ @ 133 MHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Raspberry Pi",
      "ecosystem": "Pico",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/raspberry-pi-pico-w",
    "namespace": "boards",
    "name": "raspberry-pi-pico-w",
    "description": "RP2040 dual-core ARM Cortex-M0+ @ 133 MHz (Wi-Fi)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 11914,
          "pid": 10,
          "architecture": "RP2040 dual-core ARM Cortex-M0+ @ 133 MHz (Wi-Fi)"
        }
      ],
      "capabilities": [
        "analog_read",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Raspberry Pi",
      "ecosystem": "Pico",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/raspberry-pi-pico2",
    "namespace": "boards",
    "name": "raspberry-pi-pico2",
    "description": "RP2350 dual-core ARM Cortex-M33 @ 150 MHz",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 11914,
          "pid": 4,
          "architecture": "RP2350 dual-core ARM Cortex-M33 @ 150 MHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Raspberry Pi",
      "ecosystem": "Pico",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/raspberry-pi-pico2-w",
    "namespace": "boards",
    "name": "raspberry-pi-pico2-w",
    "description": "RP2350 dual-core ARM Cortex-M33 @ 150 MHz + CYW43439 (Wi-Fi 4, BLE 5.2; SDK CDC id shared with pico-w)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 11914,
          "pid": 10,
          "architecture": "RP2350 dual-core ARM Cortex-M33 @ 150 MHz + CYW43439 (Wi-Fi 4, BLE 5.2; SDK CDC id shared with pico-w)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "pwm",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Raspberry Pi",
      "ecosystem": "Pico",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/sipeed-6plus1-mic-array",
    "namespace": "boards",
    "name": "sipeed-6plus1-mic-array",
    "description": "STM32F103 @ 72 MHz, 6+1 MEMS microphone array with USB audio (UAC1)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 11012,
          "pid": 254,
          "architecture": "STM32F103 @ 72 MHz, 6+1 MEMS microphone array with USB audio (UAC1)"
        }
      ],
      "capabilities": [
        "audio_sample",
        "gpio"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Sipeed",
      "ecosystem": "MaixSense",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/sparkfun-thing-plus-esp32-c6",
    "namespace": "boards",
    "name": "sparkfun-thing-plus-esp32-c6",
    "description": "ESP32-C6 RISC-V @ 160 MHz (Wi-Fi 6, BLE 5, 802.15.4; CH340 USB-UART; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 6790,
          "pid": 29987,
          "architecture": "ESP32-C6 RISC-V @ 160 MHz (Wi-Fi 6, BLE 5, 802.15.4; CH340 USB-UART; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "ble",
        "gpio",
        "i2c",
        "microsd",
        "spi",
        "thread",
        "wifi"
      ],
      "connectors": [
        "featherwing",
        "qwiic"
      ],
      "vendor": "SparkFun",
      "ecosystem": "Thing Plus",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/stm32h7-discovery",
    "namespace": "boards",
    "name": "stm32h7-discovery",
    "description": "ARM Cortex-M7 @ 480 MHz (STM32H750, external flash)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 1155,
          "pid": 14168,
          "architecture": "ARM Cortex-M7 @ 480 MHz (STM32H750, external flash)"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "dac",
        "flash",
        "gpio",
        "i2c",
        "pwm",
        "rtt",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "STMicroelectronics",
      "ecosystem": "Discovery",
      "transport": "probe"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/teensy-4.1",
    "namespace": "boards",
    "name": "teensy-4.1",
    "description": "NXP i.MX RT1062 ARM Cortex-M7 @ 600 MHz",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 5824,
          "pid": 1155,
          "architecture": "NXP i.MX RT1062 ARM Cortex-M7 @ 600 MHz"
        }
      ],
      "capabilities": [
        "analog_read",
        "analog_write",
        "can",
        "gpio",
        "i2c",
        "pwm",
        "spi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "PJRC",
      "ecosystem": "Teensy",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/waveshare-esp32-s3-touch-lcd-2.1",
    "namespace": "boards",
    "name": "waveshare-esp32-s3-touch-lcd-2.1",
    "description": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz, 2.1\" round touch LCD, I2S speaker",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 33077,
          "architecture": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz, 2.1\" round touch LCD, I2S speaker"
        }
      ],
      "capabilities": [
        "audio_sample",
        "ble",
        "display",
        "gpio",
        "i2c",
        "spi",
        "touch",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Waveshare",
      "ecosystem": "ESP32-S3 Touch LCD",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/xiao-esp32c5",
    "namespace": "boards",
    "name": "xiao-esp32c5",
    "description": "ESP32-C5 RISC-V @ 240 MHz, dual-band 2.4/5 GHz Wi-Fi 6, BLE 5, 802.15.4 (native USB; shared VID/PID)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 12346,
          "pid": 4097,
          "architecture": "ESP32-C5 RISC-V @ 240 MHz, dual-band 2.4/5 GHz Wi-Fi 6, BLE 5, 802.15.4 (native USB; shared VID/PID)"
        }
      ],
      "capabilities": [
        "analog_read",
        "battery",
        "ble",
        "gpio",
        "i2c",
        "spi",
        "thread",
        "wifi",
        "zigbee"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Seeed Studio",
      "ecosystem": "XIAO",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "boards/xiao-esp32s3-sense",
    "namespace": "boards",
    "name": "xiao-esp32s3-sense",
    "description": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz, OV2640 camera, PDM microphone",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "usb_ids": [
        {
          "vid": 10374,
          "pid": 88,
          "architecture": "ESP32-S3 Xtensa LX7 dual-core @ 240 MHz, OV2640 camera, PDM microphone"
        }
      ],
      "capabilities": [
        "analog_read",
        "audio_sample",
        "ble",
        "camera_capture",
        "gpio",
        "i2c",
        "sensor_read",
        "spi",
        "wifi"
      ],
      "connectors": [
        "bare"
      ],
      "vendor": "Seeed Studio",
      "ecosystem": "XIAO",
      "transport": "serial"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/ads1115",
    "namespace": "electronic",
    "name": "ads1115",
    "description": "TI ADS1115 — 16-bit 4-channel ADC with programmable gain",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 72,
      "capabilities": [
        "analog_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/aht20",
    "namespace": "electronic",
    "name": "aht20",
    "description": "ASAIR AHT20 — temperature and humidity sensor",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 56,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/bme280",
    "namespace": "electronic",
    "name": "bme280",
    "description": "Bosch BME280 — temperature, humidity, and pressure sensor",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 118,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/bmp388",
    "namespace": "electronic",
    "name": "bmp388",
    "description": "Bosch BMP388 — high-accuracy barometric pressure and temperature",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 119,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/bno055",
    "namespace": "electronic",
    "name": "bno055",
    "description": "Bosch BNO055 — 9-DOF IMU with on-chip sensor fusion (absolute orientation)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 40,
      "capabilities": [
        "imu",
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "stemma_qt"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/c-0603",
    "namespace": "electronic",
    "name": "Capacitor, 0603 (1608 metric)",
    "description": "Generic MLCC family. Capacitance, dielectric, tolerance and voltage rating are properties of the BOM line, not of this entry: a design says '100n X7R 16V' and sourcing picks a manufacturer part. This entry fixes the package only.",
    "source": {
      "citation": "IPC-SM-782A body size for 0603 (1608 metric), page 76, as cited by KiCad footprint Capacitor_SMD:C_0603_1608Metric. TODO(source): dielectric, tolerance and voltage ratings are vendor-specific and belong to a chosen MPN, not to the family.",
      "url": "https://www.pcb-3d.com/wordpress/wp-content/uploads/ipc-sm-782a_amendment_1_and_2.pdf",
      "retrieved": "2026-08-15"
    },
    "attributes": {
      "package": "0603 (1608 metric)",
      "body_length_mm": 1.6,
      "body_width_mm": 0.8,
      "terminals": 2,
      "mounting": "smd"
    },
    "links": {
      "kicad_footprint": "Capacitor_SMD:C_0603_1608Metric",
      "kicad_symbol": "Device:C"
    }
  },
  {
    "schema_version": 0,
    "id": "electronic/dht11",
    "namespace": "electronic",
    "name": "dht11",
    "description": "AOSONG DHT11 — basic humidity and temperature sensor, single-wire protocol",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "gpio",
      "default_i2c_addr": null,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/dht22",
    "namespace": "electronic",
    "name": "dht22",
    "description": "AOSONG DHT22 (AM2302) — capacitive humidity and temperature sensor, single-wire protocol",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "gpio",
      "default_i2c_addr": null,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [
        "esp32-s3",
        "nanopi-neo3",
        "raspberry-pi-4",
        "raspberry-pi-5",
        "waveshare-esp32-s3-touch-lcd-2.1",
        "xiao-esp32s3-sense"
      ],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/ds18b20",
    "namespace": "electronic",
    "name": "ds18b20",
    "description": "Maxim DS18B20 — 1-Wire digital temperature sensor",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "onewire",
      "default_i2c_addr": null,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/dynamixel-xm430-w350",
    "namespace": "electronic",
    "name": "ROBOTIS Dynamixel XM430-W350-T/R",
    "description": "Smart servo with a contactless absolute encoder, so unlike a PWM hobby servo it can report where it actually is. Torque and speed are deliberately not entry facts here: ROBOTIS publishes stall torque at three supply voltages and no continuous rating at all, which makes them voltage-indexed curves rather than single values, and the vendor states outright that stall torque is not the continuous output rating.",
    "source": {
      "citation": "ROBOTIS e-Manual, Dynamixel XM430-W350, Specifications table",
      "url": "https://emanual.robotis.com/docs/en/dxl/x/xm430-w350/",
      "retrieved": "2026-08-22"
    },
    "attributes": {
      "capabilities": [
        "actuate"
      ],
      "mass_g": 82,
      "gear_ratio": 353.5,
      "position_sensor": "contactless absolute encoder, 12-bit over 360 degrees",
      "operating_temp_min_c": -5,
      "operating_temp_max_c": 80
    },
    "links": {
      "datasheet": "https://emanual.robotis.com/docs/en/dxl/x/xm430-w350/"
    }
  },
  {
    "schema_version": 0,
    "id": "electronic/grove-vision-ai-v2",
    "namespace": "electronic",
    "name": "grove-vision-ai-v2",
    "description": "Seeed Grove Vision AI Module V2 — Himax WiseEye2 (Cortex-M55 + Ethos-U55 microNPU) smart camera",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 98,
      "capabilities": [
        "camera_capture",
        "nn_accel"
      ],
      "compatible_boards": [],
      "connector": "grove"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/ili9341",
    "namespace": "electronic",
    "name": "ili9341",
    "description": "ILITEK ILI9341 — 240x320 SPI TFT LCD controller",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "spi",
      "default_i2c_addr": null,
      "capabilities": [
        "display"
      ],
      "compatible_boards": [
        "cyd-esp32-2432s028r"
      ],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/ina260",
    "namespace": "electronic",
    "name": "ina260",
    "description": "TI INA260 — high/low-side current, voltage, and power monitor",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 64,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/inmp441",
    "namespace": "electronic",
    "name": "inmp441",
    "description": "InvenSense INMP441 — I2S MEMS microphone (audio capture)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2s",
      "default_i2c_addr": null,
      "capabilities": [
        "audio_sample"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/lsm6ds3",
    "namespace": "electronic",
    "name": "lsm6ds3",
    "description": "ST LSM6DS3 — 6-axis IMU (accelerometer + gyroscope)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 106,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/max17048",
    "namespace": "electronic",
    "name": "max17048",
    "description": "Maxim MAX17048 — LiPo battery fuel gauge (state of charge)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 54,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/max31855",
    "namespace": "electronic",
    "name": "max31855",
    "description": "Maxim MAX31855 — thermocouple-to-digital converter (K-type)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "spi",
      "default_i2c_addr": null,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/max98357a",
    "namespace": "electronic",
    "name": "max98357a",
    "description": "Maxim MAX98357A — I2S Class-D amplifier (speaker output)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2s",
      "default_i2c_addr": null,
      "capabilities": [
        "audio_output"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/mcp23017",
    "namespace": "electronic",
    "name": "mcp23017",
    "description": "Microchip MCP23017 — 16-bit I2C GPIO expander",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 33,
      "capabilities": [
        "gpio"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/mcp4725",
    "namespace": "electronic",
    "name": "mcp4725",
    "description": "Microchip MCP4725 — 12-bit single-channel DAC",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 96,
      "capabilities": [
        "dac"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/mpu6050",
    "namespace": "electronic",
    "name": "mpu6050",
    "description": "InvenSense MPU-6050 — 6-axis accelerometer + gyroscope",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 104,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/ov2640",
    "namespace": "electronic",
    "name": "ov2640",
    "description": "OmniVision OV2640 — 2 MP camera image sensor (SCCB control bus)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "sccb",
      "default_i2c_addr": null,
      "capabilities": [
        "camera_capture"
      ],
      "compatible_boards": [
        "esp32-cam",
        "esp32-s3-cam",
        "xiao-esp32s3-sense"
      ],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/pca9685",
    "namespace": "electronic",
    "name": "pca9685",
    "description": "NXP PCA9685 — 16-channel 12-bit I2C PWM / servo driver",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 64,
      "capabilities": [
        "actuate",
        "pwm"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/pcf8574",
    "namespace": "electronic",
    "name": "pcf8574",
    "description": "NXP PCF8574 — 8-bit I2C GPIO expander",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 32,
      "capabilities": [
        "gpio"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/r-0603",
    "namespace": "electronic",
    "name": "Resistor, 0603 (1608 metric)",
    "description": "Generic chip resistor family. Resistance, tolerance and power rating are properties of the BOM line, not of this entry: a design says '4.7k 1%' and sourcing picks a manufacturer part. This entry fixes the package only.",
    "source": {
      "citation": "IPC-SM-782A body size for 0603 (1608 metric), page 72, as cited by KiCad footprint Resistor_SMD:R_0603_1608Metric. TODO(source): tolerance, power and voltage ratings are vendor-specific and belong to a chosen MPN, not to the family.",
      "url": "https://www.pcb-3d.com/wordpress/wp-content/uploads/ipc-sm-782a_amendment_1_and_2.pdf",
      "retrieved": "2026-08-15"
    },
    "attributes": {
      "package": "0603 (1608 metric)",
      "body_length_mm": 1.6,
      "body_width_mm": 0.8,
      "terminals": 2,
      "mounting": "smd"
    },
    "links": {
      "kicad_footprint": "Resistor_SMD:R_0603_1608Metric",
      "kicad_symbol": "Device:R"
    }
  },
  {
    "schema_version": 0,
    "id": "electronic/rpi-ai-camera-imx500",
    "namespace": "electronic",
    "name": "rpi-ai-camera-imx500",
    "description": "Raspberry Pi AI Camera — Sony IMX500 12.3MP sensor with on-sensor NN inference accelerator (CSI)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "csi",
      "default_i2c_addr": null,
      "capabilities": [
        "camera_capture",
        "npu"
      ],
      "compatible_boards": [
        "raspberry-pi-4",
        "raspberry-pi-5"
      ],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/rpi-ai-hat-plus-13t",
    "namespace": "electronic",
    "name": "rpi-ai-hat-plus-13t",
    "description": "Raspberry Pi AI HAT+ (13 TOPS) — Hailo-8L NPU over PCIe Gen3 (RPi 5)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "pcie",
      "default_i2c_addr": null,
      "capabilities": [
        "hailo"
      ],
      "compatible_boards": [
        "raspberry-pi-5"
      ],
      "connector": "hat_pi"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/rpi-ai-hat-plus-2",
    "namespace": "electronic",
    "name": "rpi-ai-hat-plus-2",
    "description": "Raspberry Pi AI HAT+ 2 — Hailo-10H NPU, 40 TOPS INT4 / 20 TOPS INT8, GenAI-capable (RPi 5, PCIe)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "pcie",
      "default_i2c_addr": null,
      "capabilities": [
        "hailo"
      ],
      "compatible_boards": [
        "raspberry-pi-5"
      ],
      "connector": "hat_pi"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/scd41",
    "namespace": "electronic",
    "name": "scd41",
    "description": "Sensirion SCD41 — true CO2 (photoacoustic NDIR), temperature, humidity",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 98,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "qwiic"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/sg90",
    "namespace": "electronic",
    "name": "sg90",
    "description": "TowerPro SG90 — micro servo (PWM position control)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "pwm",
      "default_i2c_addr": null,
      "capabilities": [
        "actuate"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/sgp40",
    "namespace": "electronic",
    "name": "sgp40",
    "description": "Sensirion SGP40 — VOC air-quality gas sensor",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 89,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "qwiic"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/sht31",
    "namespace": "electronic",
    "name": "sht31",
    "description": "Sensirion SHT31 — high-accuracy temperature and humidity",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 68,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/sim7600",
    "namespace": "electronic",
    "name": "sim7600",
    "description": "SIMCom SIM7600 — LTE Cat-4 cellular modem with GNSS (UART/USB)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "uart",
      "default_i2c_addr": null,
      "capabilities": [
        "cellular",
        "gps"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/ssd1306",
    "namespace": "electronic",
    "name": "ssd1306",
    "description": "Solomon SSD1306 — 128x64 OLED display",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 60,
      "capabilities": [],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/tb6612fng",
    "namespace": "electronic",
    "name": "tb6612fng",
    "description": "Toshiba TB6612FNG — dual DC motor driver (PWM + direction)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "gpio",
      "default_i2c_addr": null,
      "capabilities": [
        "actuate"
      ],
      "compatible_boards": [],
      "connector": "bare"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/vl53l1x",
    "namespace": "electronic",
    "name": "vl53l1x",
    "description": "ST VL53L1X — time-of-flight distance sensor (up to 4 m)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "i2c",
      "default_i2c_addr": 41,
      "capabilities": [
        "sensor_read"
      ],
      "compatible_boards": [],
      "connector": "stemma_qt"
    },
    "links": {}
  },
  {
    "schema_version": 0,
    "id": "electronic/xpt2046",
    "namespace": "electronic",
    "name": "xpt2046",
    "description": "XPT2046 — resistive touch-screen controller (SPI)",
    "source": {
      "citation": "Oh-Ben-Claw registry/registry.json (generated from src/peripherals/registry.rs)",
      "retrieved": "2026-08-15",
      "upstream_schema_version": 1
    },
    "attributes": {
      "bus": "spi",
      "default_i2c_addr": null,
      "capabilities": [
        "touch"
      ],
      "compatible_boards": [
        "cyd-esp32-2432s028r"
      ],
      "connector": "bare"
    },
    "links": {}
  }
] as readonly Part[]);

export function partById(id: string): Part | undefined {
  return PARTS.find((p) => p.id === id);
}

export function partsIn(namespace: Namespace): readonly Part[] {
  return PARTS.filter((p) => p.namespace === namespace);
}
