#!/usr/bin/env python3
"""Emit the Rust binding from schema + data (ADR-0003).

    python scripts/emit_rust.py            # write bindings/rust/src/lib.rs
    python scripts/emit_rust.py --check    # exit 1 if the committed file is stale

Zero dependencies on purpose. Oh-Ben-Claw is the intended consumer and it
should not have to take serde to read static reference data, so everything is
`&'static` and the whole registry is a const array with no runtime parsing.

Two fields are hoisted out of `attributes` and typed: `capabilities` and
`usb_ids`. They are hoisted because they are what a consumer actually
dispatches on -- ADR-0004's point that a board is not a USB identity only
matters if `usb_ids` is a list you can iterate. Everything else stays as raw
JSON in `attributes_json`, so a niche field never forces a schema change here.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "bindings" / "rust" / "src" / "lib.rs"
NAMESPACES = ("boards", "electronic", "mechanical", "material")


def rust_str(value: str) -> str:
    """Rust string literal. Escapes are the same as JSON's for our data."""
    return json.dumps(value, ensure_ascii=False)


def rust_f64(value) -> str:
    """An f64 literal with the same digits the JSON carried. `repr` of a float
    is the shortest round-tripping form, and a trailing `.0` keeps an integer
    value a float."""
    text = repr(float(value))
    return text if "." in text or "e" in text else text + ".0"


def load_entries() -> list[dict]:
    entries: list[dict] = []
    for namespace in NAMESPACES:
        directory = ROOT / "data" / namespace
        if directory.exists():
            for path in sorted(directory.glob("*.json")):
                entries.append(json.loads(path.read_text(encoding="utf-8")))
    entries.sort(key=lambda e: e["id"])
    return entries


HEADER = '''// Generated by scripts/emit_rust.py from schema/part.schema.json + data/.
// Do not edit by hand: CI regenerates this file and fails on any difference.
//
// Zero dependencies. The whole registry is const data; nothing is parsed at
// runtime.

#![forbid(unsafe_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Namespace {
    Boards,
    Electronic,
    Mechanical,
    Material,
}

impl Namespace {
    pub const fn as_str(self) -> &'static str {
        match self {
            Namespace::Boards => "boards",
            Namespace::Electronic => "electronic",
            Namespace::Mechanical => "mechanical",
            Namespace::Material => "material",
        }
    }
}

/// One USB identity a board may enumerate as.
///
/// A board can have several, and one identity can belong to several boards
/// (ADR-0004) -- `0x303a:0x1001` alone covers seventeen. Identifying hardware
/// from a USB id is therefore a match returning candidates, never a lookup.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UsbId {
    pub vid: u16,
    pub pid: u16,
    pub architecture: &'static str,
}

/// Axis-aligned bounding envelope of the physical part, millimetres.
///
/// Carries its own citation (ADR-0006): an ingested board's entry-level
/// citation is a registry that holds no dimensions, so a number under it
/// would be wearing a source that does not cover it.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EnvelopeMm {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    /// Dimensional tolerance if the source states one.
    pub tolerance_mm: Option<f64>,
    pub citation: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct Part {
    pub id: &'static str,
    pub namespace: Namespace,
    pub name: &'static str,
    pub description: &'static str,
    /// Where this entry's values come from. Never empty: uncited entries do
    /// not pass validation upstream of this file.
    pub citation: &'static str,
    pub capabilities: &'static [&'static str],
    /// Empty for anything that is not a board.
    pub usb_ids: &'static [UsbId],
    /// `None` means unknown -- never a zero. Most entries have none: the
    /// upstream registry carries no dimensions, and each envelope here was
    /// sourced separately.
    pub envelope_mm: Option<EnvelopeMm>,
    /// The namespace-specific remainder, verbatim, for consumers that need a
    /// field this binding does not hoist.
    pub attributes_json: &'static str,
}

'''

FOOTER = '''
/// Exact lookup by canonical id.
pub fn by_id(id: &str) -> Option<&'static Part> {
    PARTS.iter().find(|p| p.id == id)
}

/// Every part in a namespace.
pub fn in_namespace(namespace: Namespace) -> impl Iterator<Item = &'static Part> {
    PARTS.iter().filter(move |p| p.namespace == namespace)
}

/// Every part declaring a capability.
pub fn with_capability(capability: &str) -> impl Iterator<Item = &'static Part> + '_ {
    PARTS.iter().filter(move |p| p.capabilities.contains(&capability))
}

/// Candidate boards for a USB identity.
///
/// Returns an iterator, not an `Option`, because the mapping is genuinely
/// many-to-many (ADR-0004). A caller that wants one answer needs a second
/// signal -- a probe, or the user saying which board they own.
pub fn candidates_for_usb(vid: u16, pid: u16) -> impl Iterator<Item = &'static Part> {
    PARTS
        .iter()
        .filter(move |p| p.usb_ids.iter().any(|u| u.vid == vid && u.pid == pid))
}
'''


def render_part(entry: dict) -> str:
    attributes = entry.get("attributes") or {}
    capabilities = attributes.get("capabilities") or []
    usb_ids = attributes.get("usb_ids") or []

    caps = ", ".join(rust_str(c) for c in capabilities)
    usb = ", ".join(
        "UsbId { vid: 0x%04x, pid: 0x%04x, architecture: %s }"
        % (u["vid"], u["pid"], rust_str(u.get("architecture") or ""))
        for u in usb_ids
    )
    # Canonical JSON so the emitted file is stable across runs and platforms.
    attributes_json = json.dumps(attributes, sort_keys=True, separators=(",", ":"))

    envelope = entry.get("envelope_mm")
    if envelope is None:
        envelope_rs = "None"
    else:
        tol = envelope.get("tolerance_mm")
        envelope_rs = (
            "Some(EnvelopeMm { x: %s, y: %s, z: %s, tolerance_mm: %s, citation: %s })"
            % (
                rust_f64(envelope["x"]),
                rust_f64(envelope["y"]),
                rust_f64(envelope["z"]),
                "None" if tol is None else f"Some({rust_f64(tol)})",
                rust_str(envelope["source"]["citation"]),
            )
        )

    namespace = entry["namespace"].capitalize()
    return (
        "    Part {\n"
        f"        id: {rust_str(entry['id'])},\n"
        f"        namespace: Namespace::{namespace},\n"
        f"        name: {rust_str(entry['name'])},\n"
        f"        description: {rust_str(entry.get('description') or '')},\n"
        f"        citation: {rust_str(entry['source']['citation'])},\n"
        f"        capabilities: &[{caps}],\n"
        f"        usb_ids: &[{usb}],\n"
        f"        envelope_mm: {envelope_rs},\n"
        f"        attributes_json: {rust_str(attributes_json)},\n"
        "    },\n"
    )


def render() -> str:
    entries = load_entries()
    body = "".join(render_part(e) for e in entries)
    return (
        HEADER
        + f"pub const PARTS: &[Part] = &[\n{body}];\n"
        + FOOTER
    )


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print(f"binding missing: {OUT.relative_to(ROOT)} -- run scripts/emit_rust.py",
                  file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(
                f"binding is stale: {OUT.relative_to(ROOT)} differs from the data. "
                "Run scripts/emit_rust.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("binding up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(load_entries())} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
