#!/usr/bin/env python3
"""Emit the TypeScript binding from schema + data (ADR-0003).

Hand-rolled, stdlib only. Output is committed; CI regenerates and diffs, so a
data change that is not accompanied by a regenerated binding turns the build
red rather than drifting silently -- the parity discipline borrowed from
OBC-Prime.

Usage:
    python scripts/emit_ts.py            # write bindings/typescript/parts.ts
    python scripts/emit_ts.py --check    # exit 1 if the committed file is stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "bindings" / "typescript" / "parts.ts"
NAMESPACES = ("boards", "electronic", "mechanical", "material")

HEADER = """// Generated by scripts/emit_ts.py from schema/part.schema.json + data/.
// Do not edit by hand: CI regenerates this file and fails on any difference.

export type Namespace = {namespaces};

export interface PartSource {{
  citation: string;
  retrieved?: string;
  upstream_schema_version?: number | string;
}}

/** Axis-aligned bounding envelope, millimetres, with its own citation (ADR-0006). Absent means unknown. */
export interface PartEnvelope {{
  x: number;
  y: number;
  z: number;
  tolerance_mm?: number;
  source: {{ citation: string; url?: string; retrieved?: string }};
}}

export interface Part {{
  schema_version: 0;
  id: string;
  namespace: Namespace;
  name: string;
  description?: string;
  source: PartSource;
  attributes?: Record<string, unknown>;
  envelope_mm?: PartEnvelope;
  links?: Record<string, string>;
}}

export const PARTS: readonly Part[] = Object.freeze("""

FOOTER = """ as readonly Part[]);

export function partById(id: string): Part | undefined {
  return PARTS.find((p) => p.id === id);
}

export function partsIn(namespace: Namespace): readonly Part[] {
  return PARTS.filter((p) => p.namespace === namespace);
}
"""


def load_entries() -> list[dict]:
    entries: list[dict] = []
    for namespace in NAMESPACES:
        directory = ROOT / "data" / namespace
        if not directory.exists():
            continue
        for path in sorted(directory.glob("*.json")):
            entries.append(json.loads(path.read_text(encoding="utf-8")))
    entries.sort(key=lambda e: e["id"])
    return entries


def render() -> str:
    entries = load_entries()
    namespaces = " | ".join(f'"{n}"' for n in NAMESPACES)
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    return HEADER.format(namespaces=namespaces) + body + FOOTER


def main() -> int:
    text = render()
    check = "--check" in sys.argv[1:]

    if check:
        if not OUT.exists():
            print(f"binding missing: {OUT.relative_to(ROOT)} -- run scripts/emit_ts.py", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(
                f"binding is stale: {OUT.relative_to(ROOT)} differs from the data. "
                "Run scripts/emit_ts.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("binding up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(load_entries())} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
